version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet build movie-service-aws-dynamodb/MovieApi.csproj
  post_build:
    commands:
      -  dotnet publish -r linux-x64 movie-service-aws-dynamodb/MovieApi.csproj
artifacts:
  files: 
    - movie-service-aws-dynamodb/bin/Release/net8.0/linux-x64/publish/**/*
  discard-paths: yes